### ISSUE TITLE
Examples to work with IRIS from Django

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/ideas-and-innovations#10]
Django is a Python based web framework: https://www.djangoproject.com/

Need a series of examples on how to build solutions with IRIS

**Comment by pjsulin** [comment]
Connecting Django to IRIS requires writing a backend package for IRIS. The currently implemented backends can be found here: https://github.com/django/django/tree/master/django/db/backends

There is a good high level overview of the requirements of this package in this video from 3:45 to about 17:00: https://www.youtube.com/watch?v=tkwZ1jG3XgA

An important factor in determining scope is knowing how much code will have to be changed in the SQLCompiler. The base class is in a different package, django.db.models.sql, and the existing implementations have very little or no code in a compiler subclass. For a more complete example of possible changes necessary, look at the unofficial MSSQL backend implementation: https://github.com/michiya/django-pyodbc-azure/tree/azure-2.1/sql_server/pyodbc.

**Comment by evshvarov** [comment]
[Moved](https://isc-community.ideas.aha.io/ideas/DP-I-168)
