### ISSUE TITLE
IMAP Interoperability Adapter

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/ideas-and-innovations#16]

**Comment by diashenrique** [comment]
Can we have more details about the IMAP Interoperability Adapter? 
I only found information about EnsLib.EMail.OutboundAdapter on InterSystems IRIS Data Platform 2020.2 documentation.

**Comment by evshvarov** [comment]
Hi @diashenrique -  it's a request for "Good to have this" :)

**Comment by evshvarov** [comment]
For both "Inbound and Outbound I think. Calling @eduard93 for more details

**Comment by eduard93** [comment]
I think only Inbound Adapter is required.
IMAP is used to receive emails so Inbound Adapter + Business Service it is.

**Comment by eduard93** [comment]
We support sending mail via SMTP.

**Comment by irinapodmazko** [comment]
https://community.intersystems.com/post/implementing-imap-client-intersystems-iris-part-ii
