### ISSUE TITLE
AI Solution for Indexing: analyze queries being used and make indexing using this

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/ideas-and-innovations#22]

**Comment by eduard93** [comment]
Not sure about queries, but there's some ideas for indexing.
Check this article: [PGM Indexes: Learned indexes that match B-tree performance with 83x less space](https://pgm.di.unipi.it/).

**Comment by evshvarov** [comment]
[Moved](https://isc-community.ideas.aha.io/ideas/DP-I-170)
