### ISSUE TITLE
Support for mainstream protocols

### ISSUE THREAD

**Issue by hermanslagman** [intersystems-community/ideas-and-innovations#28]
One can argue 'mainstream' with protocols, but a number of them seem to be in the realm of IRIS:
- MQTT for IOT edge communication (Raspberry Pi and the like)
- gRPC for very efficient and fast communication in MicroServices infrastructure (instead of TCP/HTTP)

**Comment by eduard93** [comment]
MQTT is available by default.

Consider closing in favor of https://github.com/intersystems-community/dc_innovations/issues/49

**Comment by eduard93** [comment]
@evshvarov close it?

**Comment by hermanslagman** [comment]
OK

**Comment by evshvarov** [comment]
What about gRPC? @eduard93 ? Should we create a new one?

**Comment by daimor** [comment]
> What about gRPC? @eduard93 ? Should we create a new one?

already, #49

**Comment by evshvarov** [comment]
OK, closing.
