### ISSUE TITLE
Introduce one-line ObjectScript command to traverse global on a certain level

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/ideas-and-innovations#31]
If you need to go through all the records on the level of Global array you do:
set key=$Order(^Data(""))
while key'="" {
// do someting
set key=$Order(^Data(key)
}

We better have:
while $Next(^Data(.key)) {
// do something
}

Cause you don't need to put extra line every time in this case

**Comment by rcemper** [comment]
do you look for something like this ?

#define foreach(%key,%arr,%do) set %key=$o(%arr("")) for  set %key="" quit:%key=""  do %do

using it:
a $$$foreach(key,^rcc(27),b)
	quit
b zwrite @$zr,! quit

**Comment by rcemper** [comment]
It's done. Available in OEX & ZPM
[FOREACH for ObjectScript](https://openexchange.intersystems.com/package/FOREACH-for-ObjectScript)

**Comment by rcemper** [comment]
same as [issue #32](https://github.com/intersystems-community/ideas-and-innovations/issues/31)

**Comment by evshvarov** [comment]
Closing because it's done!
