### ISSUE TITLE
Introduce for each for global traversing

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/ideas-and-innovations#32]
instead of:
``` 
set key="" for {
set key=$O(^array(key)) q:iter=""
// do something
}
```
introduce:
```
foreach key in ^array {
// do something
}

**Comment by rcemper** [comment]
do you look for something like this ?

#define foreach(%key,%arr,%do) set %key=$o(%arr("")) for  set %key=$o(%arr(%key)) quit:%key=""  do %do

using it:
a $$$foreach(key,^rcc(27),b)
	quit
b zwrite @$zr,! quit

**Comment by evshvarov** [comment]
Looks as what I'm looking for.
Ideally to have a zpm module with all these macro related to Global
traversing

**Comment by rcemper** [comment]
Just a minor adjustment:

#define foreach(%key,%arr,%do) *set %key=""* for set 
 >%key=$o(%arr(%key)) quit:%key="" do %do

I'm trying it just now also as ZFOREACH()  in %ZLANGF00.
It my take some time.

Robert

Am 16.02.2021 um 12:11 schrieb Evgeny Shvarov:
> Looks as what I'm looking for.
> Ideally to have a zpm module with all these macro related to Global
> traversing
>

**Comment by rcemper** [comment]
It's done. available  in OEX+ZPM for COS and ISOS
[FOREACH for ObjectScript](https://openexchange.intersystems.com/package/FOREACH-for-ObjectScript)

**Comment by rcemper** [comment]
same as [issue #31](https://github.com/intersystems-community/ideas-and-innovations/issues/31)

**Comment by evshvarov** [comment]
Closing as it is done
