### ISSUE TITLE
IRIS Monitoring Article 

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/ideas-and-innovations#36]
https://irisdocs.intersystems.com/iris20194/csp/docbook/DocBook.UI.Page.cls?KEY=GCM_rest

**Comment by diashenrique** [comment]
Maybe this article can cover most parts of how to use the custom monitoring API
https://community.intersystems.com/post/iris-history-monitor-using-custom-built-rest-api-apimonitormetrics

**Comment by evshvarov** [comment]
done
