### ISSUE TITLE
Package Manager for InterSystems Data Platforms

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/ideas-and-innovations#5]

**Comment by eduard93** [comment]
Closed with https://github.com/intersystems-community/zpm

**Comment by evshvarov** [comment]
Done https://openexchange.intersystems.com/package/ObjectScript-Package-Manager

**Comment by rcemper** [comment]
Just to be precise: 
- it is not for InterSystems Data Platforms in general (no Caché, no Ensemble, ...)
- it is only for InterSystems IRIS based Data Platforms

**Comment by evshvarov** [comment]
But somebody ported it for Caché, no?

**Comment by rcemper** [comment]
Where is it available?
