### ISSUE TITLE
Security settings for mirror configurations

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/ideas-and-innovations#51]
Currently, there is no way to mirror security settings and configurations.
Need a lib/tool to provide security settings mirroring capabilities

**Comment by lscalese** [comment]
Hi,

I recently developped tools to do that.
I'll write an article.

**Comment by evshvarov** [comment]
Wow! Looking forward!

Вс, 17 окт. 2021 г. в 02:26, Lorenzo Scalese ***@***.***>:

**Comment by evshvarov** [comment]
[Moved](https://isc-community.ideas.aha.io/ideas/DP-I-152)
