### ISSUE TITLE
A way to access the database in a different way from the WEB. A homemade solution.

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/ideas-and-innovations#52]

**Comment by eduard93** [comment]
Close it?

**Comment by evshvarov** [comment]
[This is it.](https://community.intersystems.com/post/ideas-new-applications-what-develop-2021#comment-140071)
Not sure what does the author mean here

**Comment by eduard93** [comment]
> Not sure what does the author mean here

So close it?

**Comment by evshvarov** [comment]
OK
