### ISSUE TITLE
Introduce AS2 Interoperability Adapter

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/ideas-and-innovations#64]
There is a need for the file exchange implementation of [AS2 protocol](https://en.wikipedia.org/wiki/AS2) in a form of an Interoperability (integration) adapter

**Comment by grongierisc** [comment]
With the upcoming release of Embedded python, it is possible to create an adapter with this python library: https://pypi.org/project/pyAS2/

**Comment by evshvarov** [comment]
Transferred [here](https://isc-community.ideas.aha.io/ideas/DP-I-142)
