### ISSUE TITLE
Auto-login to restricted documentation (e.g., HealthShare) for orgs/users

### ISSUE THREAD

**Issue by CraigRegester** [intersystems-community/ideas-and-innovations#66]
Would be a big people pleaser (at least with my org) if each day we accessed HealthShare docs @ docs.intersystems.com we didn't have to login yet again to access contextual help from the Management Portal. 

How? (Just a thought off the cuff) Maybe using some of the new OAuth 2.0 Client capabilities in IRIS, it would be possible for an org to get a client ID/secret from the WRC Portal to setup an OAuth 2.0 Client in each of their instances so that when docs is accessed, a URL Parameter could pass in a value that permits the org to have unfettered access (no user login required) to the online documentation. This would still need to create a valid login cookie so if documentation is accessed directly (without clicking on Help within the Management Portal), the user wouldn't need to login at that point either.

Bonus: This OAuth 2.0 Client arrangement could then also be used to securely send data to WRC logs, etc since it would be able to speak 'on behalf' of the org (with appropriate controls of course.)

**Comment by evshvarov** [comment]
Could you please reintroduce the idea on the [InterSystems Ideas portal](https://isc-community.ideas.aha.io/ideas)?
The sign in is the InterSystems SSO

**Comment by CraigRegester** [comment]
@evshvarov done, thank you for letting me know the new spot. :)
