### ISSUE TITLE
YCSB Benchmark

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/ideas-and-innovations#9]
https://github.com/brianfrankcooper/YCSB/wiki

**Comment by grongierisc** [comment]
FYI, i'm working on it for a prospect throw this fork : https://github.com/grongierisc/YCSB
I haven't finish the XEP side.
But, on JDBC sides, results are good for Iris 2019.1: 

**Bench Settings** : 
* Host : OSX Mojave + Intel i9
* Bench : 
  * 100000 rows
   * workloada of YCSB (50% insert update 50% read)
   * 4 jdbc clients threads
 * All default settings on databases and jdbc drivers

**Testing with Maria LOCAL**
[OVERALL], RunTime(ms), 7 294
[OVERALL], Throughput(ops/sec), 13 709
[OVERALL], RunTime(ms), 5 128
[OVERALL], Throughput(ops/sec), 19 500
**Testing with Maria DOCKER**
[OVERALL], RunTime(ms), 52 545
[OVERALL], Throughput(ops/sec), 1 903
[OVERALL], RunTime(ms), 36 113
[OVERALL], Throughput(ops/sec), 2 769
**Testing with Intersystems IRIS LOCAL**
[OVERALL], RunTime(ms), 3 865
[OVERALL], Throughput(ops/sec), **25 873**
[OVERALL], RunTime(ms), 3 490
[OVERALL], Throughput(ops/sec), **28 653**
**Testing with Intersystems IRIS DOCKER**
[OVERALL], RunTime(ms), 26 487
[OVERALL], Throughput(ops/sec), 3 775
[OVERALL], RunTime(ms), 22 804
[OVERALL], Throughput(ops/sec), 4 385
**Testing with PostgreSQL LOCAL**
[OVERALL], RunTime(ms), 5 359
[OVERALL], Throughput(ops/sec), **18 660**
[OVERALL], RunTime(ms), 3 609
[OVERALL], Throughput(ops/sec), **27 708**
**Testing with PostgreSQL DOCKER**
[OVERALL], RunTime(ms), 39 138
[OVERALL], Throughput(ops/sec), 2 555
[OVERALL], RunTime(ms), 31 426
[OVERALL], Throughput(ops/sec), 3 182

**Comment by evshvarov** [comment]
Hi @grongierisc! Cool stuff!
Do you want to share it on [InterSystems Developers](https://community.intersystems.com)? and the project on [Open Exchange](https://openexchange.intersystems.com)?

**Comment by evshvarov** [comment]
[Moved](https://isc-community.ideas.aha.io/ideas/DP-I-164)
